export enum EOrderStatus {
    REQUESTED = 'REQUESTED',
    ACCEPTED = 'ACCEPTED',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    SHIPPING = 'SHIPPING',
    DELIVERED = 'DELIVERED',
    CANCELED = 'CANCELED'
}